### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by DanHartman** [scaleoutllc/kubectl-build#1]
Behavior I did not expect
This works fine when I run it from within the "ops" container.  However running it locally on my mac seems to have a difficulty.

What I expected:
```
---
apiVersion: v1
kind: Blargh
metadata:
  name: KABLOOEY
```

What I got:
`patch: {"replacements":[{"path":"metadata.name","value":"KABLOOEY"}],"target":{"apiVersion":"v1","kind":"Blargh"}} matches        1 resources, wanted 1.`

#### f1.yml
```
apiVersion: v1
kind: Blargh
metadata:
  name: ${BLARGH}
```

#### assembly.yml
```
resources:
- f1.yml

vars:
- name: BLARGH
  value: KABLOOEY

patches:
- target:
    apiVersion: v1
    kind: Blargh
  replacements:
  - path: metadata.name
    value: ${BLARGH}
```
`./kubectl-build .`
